# Generated by Django 3.1.5 on 2021-02-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dbmovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dym', models.CharField(blank=True, max_length=250, null=True)),
                ('dy', models.CharField(blank=True, max_length=250, null=True)),
                ('bj', models.CharField(blank=True, max_length=250, null=True)),
                ('zy', models.TextField(blank=True, null=True)),
                ('lx', models.CharField(blank=True, max_length=200, null=True)),
                ('zpgj', models.CharField(blank=True, max_length=200, null=True)),
                ('yy', models.TextField(blank=True, null=True)),
                ('syrq', models.CharField(blank=True, max_length=200, null=True)),
                ('pc', models.CharField(blank=True, max_length=200, null=True)),
                ('ym', models.CharField(blank=True, max_length=250, null=True)),
                ('jqjj', models.TextField(blank=True, null=True)),
                ('dbpf', models.CharField(blank=True, max_length=45, null=True)),
                ('pjrs', models.CharField(blank=True, max_length=200, null=True)),
                ('gfwz', models.CharField(blank=True, max_length=250, null=True)),
                ('pfzb', models.CharField(blank=True, max_length=250, null=True)),
                ('imdbpf', models.CharField(blank=True, max_length=250, null=True)),
                ('imdbpjrs', models.CharField(blank=True, max_length=45, null=True)),
                ('hjqk', models.TextField(blank=True, null=True)),
                ('cybq', models.CharField(blank=True, max_length=250, null=True)),
                ('yjhpj', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'dbmovie',
                'managed': True,
            },
        ),
    ]
