# Generated by Django 3.1.5 on 2021-03-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dbmovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dym', models.CharField(blank=True, max_length=250, null=True, verbose_name='电影名')),
                ('dy', models.CharField(blank=True, max_length=250, null=True, verbose_name='导演')),
                ('bj', models.CharField(blank=True, max_length=250, null=True, verbose_name='编剧')),
                ('zy', models.TextField(blank=True, null=True, verbose_name='主演')),
                ('lx', models.CharField(blank=True, max_length=200, null=True, verbose_name='类型')),
                ('zpgj', models.CharField(blank=True, max_length=200, null=True, verbose_name='制片国家')),
                ('yy', models.TextField(blank=True, null=True, verbose_name='语言')),
                ('syrq', models.CharField(blank=True, max_length=200, null=True, verbose_name='上映日期')),
                ('pc', models.CharField(blank=True, max_length=200, null=True, verbose_name='片长')),
                ('ym', models.CharField(blank=True, max_length=250, null=True, verbose_name='原名')),
                ('jqjj', models.TextField(blank=True, null=True, verbose_name='剧情简介')),
                ('dbpf', models.CharField(blank=True, max_length=45, null=True, verbose_name='豆瓣评分')),
                ('pjrs', models.CharField(blank=True, max_length=200, null=True, verbose_name='豆瓣评价人数')),
                ('gfwz', models.CharField(blank=True, max_length=250, null=True, verbose_name='官方网站')),
                ('pfzb', models.CharField(blank=True, max_length=250, null=True, verbose_name='评分占比')),
                ('imdbpf', models.CharField(blank=True, max_length=250, null=True, verbose_name='imdb评分')),
                ('imdbpjrs', models.CharField(blank=True, max_length=45, null=True, verbose_name='imdb评价人数')),
                ('hjqk', models.TextField(blank=True, null=True, verbose_name='获奖情况')),
                ('cybq', models.CharField(blank=True, max_length=250, null=True, verbose_name='常用标签')),
                ('yjhpj', models.CharField(blank=True, max_length=250, null=True, verbose_name='一句话评价')),
            ],
            options={
                'db_table': 'dbmovie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('pmid', models.IntegerField(primary_key=True, serialize=False)),
                ('pm_pid', models.IntegerField(blank=True, null=True, verbose_name='父id')),
                ('pmname', models.CharField(blank=True, max_length=50, null=True, verbose_name='权限名称')),
                ('pmurl', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限路径')),
                ('pmlevel', models.IntegerField(blank=True, null=True, verbose_name='权限等级')),
                ('pmaction', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作动作')),
            ],
            options={
                'db_table': 'Permission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleid', models.IntegerField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(blank=True, max_length=50, null=True, verbose_name='角色名称')),
                ('roledec', models.CharField(blank=True, max_length=50, null=True, verbose_name='角色说明')),
                ('pmids', models.IntegerField(blank=True, null=True, verbose_name='权限id集合')),
            ],
            options={
                'db_table': 'Role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名')),
                ('userpassword', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户密码')),
                ('usersex', models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别')),
                ('usereducation', models.IntegerField(blank=True, choices=[(1, '高中'), (2, '本科'), (3, '硕士'), (4, '博士')], null=True)),
                ('userbirthday', models.DateField(blank=True, null=True, verbose_name='用户密码')),
                ('roleid', models.IntegerField(blank=True, null=True, verbose_name='角色id')),
                ('usertype', models.IntegerField(blank=True, choices=[(1, '普通用户'), (2, 'VIP'), (3, 'SVIP')], null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='状态')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movieapi.user')),
            ],
            options={
                'db_table': 'UserToken',
                'managed': True,
            },
        ),
    ]
