# Generated by Django 3.1.5 on 2021-03-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='pmids',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='权限id集合'),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
