# Generated by Django 3.1.5 on 2021-03-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userpassword',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='用户密码'),
        ),
    ]
