# Generated by Django 3.1.5 on 2021-03-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0002_auto_20210307_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userbirthday',
            field=models.DateField(blank=True, null=True, verbose_name='用户密码'),
        ),
    ]
