# Generated by Django 3.1.5 on 2021-03-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0002_auto_20210313_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='pmids',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='权限id集合'),
        ),
    ]
