# Generated by Django 3.1.5 on 2021-03-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0003_user_userbirthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('pmid', models.AutoField(primary_key=True, serialize=False)),
                ('pm_pid', models.IntegerField(blank=True, null=True, verbose_name='父id')),
                ('pmname', models.CharField(blank=True, max_length=50, null=True, verbose_name='权限名称')),
                ('pmurl', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限路径')),
                ('pmlevel', models.IntegerField(blank=True, null=True, verbose_name='权限等级')),
                ('pmaction', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作动作')),
            ],
            options={
                'db_table': 'Permission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(blank=True, max_length=50, null=True, verbose_name='角色名称')),
                ('roledec', models.CharField(blank=True, max_length=50, null=True, verbose_name='角色说明')),
                ('pmids', models.IntegerField(blank=True, null=True, verbose_name='权限id集合')),
            ],
            options={
                'db_table': 'Role',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roleid',
            field=models.IntegerField(blank=True, null=True, verbose_name='角色id'),
        ),
    ]
