# Generated by Django 3.1.5 on 2021-02-13 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dbmovie',
            table='dbmovie',
        ),
    ]
