# Generated by Django 3.1.5 on 2021-02-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210213_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbmovie',
            options={'managed': True},
        ),
    ]
