# Generated by Django 3.1.5 on 2021-02-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210213_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbmovie',
            old_name='jj',
            new_name='hjqk',
        ),
        migrations.AddField(
            model_name='dbmovie',
            name='jqjj',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dbmovie',
            name='bj',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dbmovie',
            name='dbpf',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dbmovie',
            name='dy',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dbmovie',
            name='dym',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dbmovie',
            name='imdbpjrs',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dbmovie',
            name='lx',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dbmovie',
            name='pc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dbmovie',
            name='pjrs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dbmovie',
            name='syrq',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dbmovie',
            name='ym',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dbmovie',
            name='yy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dbmovie',
            name='zpgj',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dbmovie',
            name='zy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
