# Generated by Django 3.1.5 on 2021-02-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dbbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(blank=True, max_length=200, null=True)),
                ('yjhpj', models.CharField(blank=True, max_length=200, null=True)),
                ('dbpf', models.CharField(blank=True, max_length=200, null=True)),
                ('pjrs', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('cbs', models.CharField(blank=True, max_length=200, null=True)),
                ('cbn', models.CharField(blank=True, max_length=200, null=True)),
                ('ys', models.CharField(blank=True, max_length=200, null=True)),
                ('dj', models.CharField(blank=True, max_length=200, null=True)),
                ('zz', models.CharField(blank=True, max_length=200, null=True)),
                ('cs', models.CharField(blank=True, max_length=200, null=True)),
                ('isbn', models.CharField(blank=True, max_length=200, null=True)),
                ('nrjj', models.TextField(blank=True, null=True)),
                ('zzjj', models.TextField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=200, null=True)),
                ('fbt', models.CharField(blank=True, max_length=200, null=True)),
                ('yzm', models.CharField(blank=True, max_length=200, null=True)),
                ('yz', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
